# 在此处填写登录信息
username: 'your_id_here@jxnu' # @jxnu or @cmcc or @cucc or @ctcc
password: '123'

# 以下为自定义信息
header:
  User-Agent: ['Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36']

# 以下信息不建议修改，我也不知道是啥
n: '200'
type: '1'
ac_id: '1'
enc: 'srun_bx1'