name: Build Program

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build program
        id: build
        run: |
          chmod +x ./build.sh
          ./build.sh
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MyArtifacts
          path: ${{ steps.build.outputs.artifact_path }}
          retention-days: 7
          
